# Ecuaciones diferenciales parciales de primer orden

## Curvas Características.
Curvas características una ecuación diferencial parcial de primer orden definido en un dominio $\Omega$ se expresa en forma general como una relación funcional entre la variable independientes $x = (x_1,x_2,...,x_n)\Omega$ una función desconocida $u(x)$ y sus derivadas parciales de primer orden:



$$F(x,u(x),\nabla u(x)) = 0$$


La EDP de primer orden se llama lineal cuando adquiere la forma:


$$\sum_{i=1}^{n} a_i(x) \frac{\partial u}{\partial x_i} = 0$$



Y es cuasilineal cuando se expresa como:

$$\sum_{i=1}^{n} a_i(x) \frac{\partial u}{\partial x_i} = b(x,u)$$


<br>

### El teorema de Cauchy.

El problema de Cauchy puede definirse de manera general como sigue: 


Encontrar la solución de:

$$F(x,u,\nabla (u))$$


Tal que se cumpla (condiciones):

$$u(r(s)) = \Phi (s)$, s $\in \Omega$$

<br>

### EDP lineales de primer orden en dos dimensiones.

La idea general para la construcción de la solución de una ecuación lineal de primer orden, en el caso particular:

$$A(x, y) \frac{\partial u}{\partial x} + B(x, y) \frac{\partial u}{\partial y} = 0 \text{ . . .(1)}$$

donde A y B son funciones diferenciales en una región y que no se anulan simultáneamente ningún punto $\Omega$.

Vamos a realizar una interpretación geométrica de la solución (1).

$U$ es solución de (1) sí solo sí para cada $(x, y)$ que pertenece a $\Omega$ El vector  $(A(x, y), B (x,y))$ es ortogonal el gradiente de $U$.

$$\vec{v} = (A(x,y),B(x,y))$$

$$u(x, y) = \left( \frac{\partial u}{\partial x}, \frac{\partial u}{\partial y} \right)$$

$$\vec{v} u = (A(x,y) ( \frac{\partial u}{\partial x}) + B(x,y)  \frac{\partial u}{\partial y})$$

Esto también lo podemos interpretar como $(A,B)$ $\perp$ sí solo si la derivada de $U$ en la dirección de $(A,B)$ es nula.

Consideremos las curvas $\tau$ en $\Omega$ expresadas paramétricamente en la forma ${x(t),y(t)}$ cuyos vectores tangentes en cada punto son colineales a $(A(x(t),y(t)),B(x(t),y(t))$.

Estas curvas satisfacen el sistema de ecuaciones diferenciales.

$$\frac{dx}{dt} = A(x, y)$$

$$\frac{dy}{dt} = B(x, y)$$

O bien podemos escribir:

$$\frac{B(x,y)}{A(x,y)} = \frac{dy}{dx}$$

O equivalentemente:

$$\frac{dx}{A(x,y)}=\frac{dy}{B(x,y)}$$

Las cuales se llaman curvas características.

Observación:

Como

$$\frac{dx}{dt} = A(x,y)$$

$$\frac{dy}{dt} = B(x,y)$$

$$A(x,y) \frac{\partial u}{\partial x} + B(x,y)  \frac{\partial u}{\partial y} = 0$$

Entonces:

$$\frac{\partial u}{\partial x} \frac{dx}{dt} + \frac{\partial u}{\partial y} \frac{dy}{dt} = 0$$

Que es la derivada total.

$$\frac{du}{dt} = 0$$

u es constante en las curvas características.

Es decir las curvas características son curvas de nivel de la superficies integrales que corresponden a las soluciones.

Consideremos ahora la curva $\gamma = ({ \gamma_1 (\theta), \gamma_2 (\theta) })$ en que ningún punto sea tangente a la curva característica y además corta cada curva característica en un solo punto.

Bajo esta suposiciones se dice que la curva $\gamma$ satisface la condición de transversalidad. Entonces, con respecto a $\gamma$ y las curvas características, se puede definir un nuevo sistema de coordenadas en $\Omega$ el cual cada punto p de coordenadas $(x,y)$ se le hace corresponder las nuevas coordenadas $(\theta, t)$, teta es el parámetro en el punto sobre $\gamma$ que intersecta la característica que contiene a p y t es el valor del parámetro que corresponde p en la característica.

Sin pérdida de generalidad el valor $t=0$ corresponde a los puntos de intersección de cada curva característica con la curva $\gamma$.

La correspondencia es biyectiva lo cual se expresa analíticamente como:

$$x = X(\theta,t)$$

$$y = Y(\theta,t)$$

$$\theta = \Theta (x,y)$$

$$t = T(x,y)$$

En las variables $(\theta,t)$ las ecuaciones de las curvas características adquieren la forma.

$$\frac{d \theta}{dt} = 0$$

ya que el valor de $\theta$ es constante sobre cada característica, es decir:

$\Theta (x,y) = C$,  $\forall (x,y)$ con C - constante

que es una misma característica.

Ejemplo sobre características:
 
Considera la EDP

$$U_x + U_y + xy \, u^2 = 0$$

$$xU_x + yU_y + U = 0$$

Identificamos 
$A(x,y) = x$ 
$B(x,y) =y$

$$\frac{dy}{dx} = \frac{y}{x}$$

$$\frac{dy}{y} = \frac{dx}{x}$$

$$\ln |y| = \ln |x| + C$$ 

$$e^{\ln |y|} = e^ {\ln |x| + C}$$

$$y = m x $$
con m constante.

**Ejemplo 3:**

$$sen(y)U_x + cos(x)U_y + u^3 = 0$$

Identificamos 
$A(x,y) = sen(y)$ 
$B(x,y) = cos(x)$

$$sen (y) dy = cos (x) dx$$

$$\int sen (y) dy = \int cos (x) dx$$

$$- cos (y) = sen (x) + C, C-constante$$

$$cos (y) = -sen (x) + C_1, C_1 - constante$$

$$y = arc(-sen(x)+ C_1))$$

En las variables $(\theta, t)$ se puede obtener fácilmente la solución de la EDP.

$$A \frac{\partial U}{\partial x} + B \frac{\partial U}{\partial y} = 0$$

Si para la solución u se hace el cambio de variables:

$$U(x,y) = U(x(\theta, t), y(\theta,t )) = v(\theta, t)$$

es decir, se cumple que para cada $\theta$ fijo $(\theta_0):$

$$(x(\theta_0,t), y(\theta_0,t)) = (x(t),y(t))$$

Es la parametrización en $t$ de la curva característica que intersecta a $\gamma$ en $\theta_0$, por ello:

$$\frac{\partial U}{\partial t} = \frac{\partial U}{\partial x} \frac{\partial x}{\partial t} + \frac{\partial U}{\partial y} \frac{\partial y}{\partial t} = \frac{\partial U}{\partial x} \frac{ dx}{dt} + \frac{\partial U}{\partial y} \frac{dy}{dt}$$

$$= A \frac{\partial U}{\partial x} + B \frac{\partial U}{\partial y} = 0$$

Podemos decir que la EDP (1) se reduce a

$$\frac{\partial v}{\partial t} = 0$$

$v = F(\theta)$, función de theta, en consecuencia $u(x,y) = F(\theta(x,y))$, tener en consideración que F es una función derivable.

**Ejemplo analógo**

¿Bajo qué condiciones es posible obtener una solución única de la ecuación (1)?
Considerar una curva $\gamma$ que satisface la condición de transversalidad con respecto a las curvas características de la ecuación (1) y parametrizada mediante 

$$(x(\theta),y(\theta)) = w (\theta)$$

Se dirá que un satisface la condición de Cauchy sobre $\gamma$ si los valores de u en $\gamma$ coinciden con los valores de una función dada w.

$$u(x, y) \big|_{\gamma} = U (x(\theta),y(\theta)) = w(\theta)$$

A la función $(\theta)$ se le llama dato de Cauchy sobre $\gamma$.

Sí $\phi(x,y)$ es una función diferenciable que es constante sobre las curvas características de la EDP,entonces cada valor fijo del parámetro $\xi$ determina una curva característica de dicha ecuación dada por:

$$\tau_\xi = ((x,y) : \phi(x,y) = \xi)$$

Al resolver la ecuación $\phi (x(s),y(s)) = \xi$ se obtiene el único valor $\beta(\xi)$ del parámetro s (encontrar el valor de s) que corresponde al punto de intersección $(x(\beta(\xi)), y(\beta(\xi)))$ de la curva $\gamma$ con la curva característica $\tau_\xi$.

De esta manera se puede representar el dato de Cauchy $w(s)$ con respecto al parámetro $\xi$ mediante $w(\beta(\xi))$ y como sobre toda la curva característica $\tau_\xi$ se tiene $\phi(x,y) = \xi$ entonces:

$$u(x, y) \big|_{\gamma} = w(s) = w(\beta(\xi)) = w(\beta(\phi(x,y)))$$

Recordando que $U (x,y) = F(\theta(x,y)) = F(\phi (x,y))$

El que la expresión $U(x,y) = w(\beta(\phi(x,y)))$ sea la única solución del problema de Cauchy se desprende del hecho de que si el problema tuviera dos soluciones $U_1, U_2$ 
Entonces $U = U_1 - U_2$ sería solución de la EDP (1) con condiciones nulas de Cauchy sobre $\gamma$, pero como estas soluciones deben ser constantes sobre las características, las cuales cubren todo $\Omega$ se concluye que en $U = 0$ en $\Omega$ y por lo tanto $U_1 = U_2$.

Cuando el dato de Cauchy se impone sobre una curva característica el correspondiente problema de Cauchy puede tener muchas soluciones o no tener solución. Sea $\tau$  una curva característica de la EDP (1), se consideran los dos siguientes casos:

**Caso 1.**

$$u(x, y) \big|_{\gamma_1} = w_0 = constante$$

En este caso si $\phi(x,y)$ es una función constante sobre las características de la ecuación parcial, tal que $\phi(x, y) \big|_{\gamma_1} = \xi_1$, entonces para cualquier función derivable $f(\xi)$  se tiene que la función $U(x,y) = f(\phi(x,y))$ es solución del correspondiente problema de Cauchy.

**Caso 2.**

$$u(x, y) \big|_{\gamma_1} \neq constante$$

En este caso no existe solución del problema de Cauchy dado que cualquier solución de la EDP (1) debe ser constante sobre las curvas características.

<br>

## Ecuaciones diferenciales parciales lineales de primer orden en dimensión n>2

En esta sección se considerará la siguiente EDP:

$$
\sum_{i=1}^{n} A_i (x_1,x_2,\ldots,x_n)\frac{\partial u}{\partial x_i} = 0
$$

donde $A_i (x_1,x_2,\ldots,x_n)$ son funciones diferenciables en la región $\Omega$ de $\mathbb{R}^2$. Las funciones $A_i$ no son nulas simultáneamente en algún punto de $\Omega$.

Las ecuaciones de las curvas paramétricas, $\Gamma$, se definen mediante el sistema de ecuaciones:

$$
\frac{dy}{dx} = A_i (x_1,x_2,\ldots,x_n)
$$

con $i= 1,2,3,\ldots,n$.

Si consideramos $t$ como el parámetro que describe la curva, tenemos:

$$
\frac{dx_1}{A_1} = \frac{dx_2}{A_2} = \ldots = \frac{dx_n}{A_n}
$$

Observación:

$$
\sum_{i=1}^{n} A_i (\vec{x})\frac{\partial u}{\partial x_i} = \sum_{i=1}^{n} \frac{dx_i}{dt}\frac{\partial u}{\partial x_i} = \frac{du}{dt} = 0
$$

Por lo tanto,

$$
\frac{du}{dt} = 0
$$

Las soluciones de la EDP son constantes sobre las curvas características. Similar al caso $n=2$, se define la primera característica como la función $\varphi(x_1,x_2,\ldots,x_n)$, la cual es diferenciable y constante en la curva característica.

Para obtener el conjunto de funciones primeras características, consideremos una superficie $S$ en $\Omega$ de $\mathbb{R}^{n-1}$ que cumple con la condición de transversalidad respecto a las curvas características:

- La curva $\Gamma$ solo intersecta a $S$ en un único punto.
- Ninguna curva característica en $\Gamma$ es tangente a $S$, es decir, el vector $\vec{A}= (A_1, A_2, \ldots, A_n)$ no está en el espacio tangente $t(\vec{x})$ de $S$.

Si la superficie $S$ está definida por la ecuación:

$$
g (x_1, x_2, \ldots, x_n) = 0
$$

el vector normal a $S$ en $(x_1, x_2, \ldots, x_n)$ es:

$$
\vec{n} (x_1, x_2, \ldots, x_n) = \nabla g (x_1, x_2, \ldots, x_n)
$$

El vector $\vec{A}= (A_1, A_2, \ldots, A_n)$ no es ortogonal a $\vec{n}$:

$$
\nabla g \cdot \vec{A} \neq 0 \Longrightarrow \vec{A} \notin t(\vec{x})
$$

Cada punto de $S$ admite una parametrización de la forma:

$$
\begin{matrix}
x_1 = x_1(\theta_1, \theta_2, \ldots, \theta_{n-1}) \\
\vdots \\
x_n = x_n(\theta_1, \theta_2, \ldots, \theta_{n-1}) 
\end{matrix}
$$

Si se construye $S$ de forma paramétrica, entonces $t(\vec{x})$ en cada punto $p(x)$ corresponde a un valor determinado de los parámetros $\theta_s$. Además, el espacio $t$ es generado por los vectores:

$$
\frac{dx}{d\theta_1}, \frac{dx}{d\theta_2}, \ldots, \frac{dx}{d\theta_n}
$$

con $x = (x_1, x_2, \ldots, x_n)$.

Dado esto, la expresión $\nabla g \cdot \vec{A} \neq 0$ indica que $\vec{A}$ no se genera con los vectores $\frac{dx}{d\theta}$. Lo podemos escribir como:

$$
\det \left(\frac{dx}{d\theta_1}, \frac{dx}{d\theta_2}, \ldots, \frac{dx}{d\theta_n}, \vec{A}\right) \neq 0
$$

Si se tiene $S$, podemos construir la solución de la ecuación diferencial de la siguiente forma:

A cada conjunto de parámetros $(\theta_1, \theta_2, \ldots, \theta_{n-1})$ se le asocia un vector $x \in S$ y a este punto le corresponde una curva característica con parámetro $t$:

$$
x_i = x_i(\theta_1, \theta_2, \ldots, \theta_{n-1}, t)
$$

con $i = 1, 2, 3, \ldots, n$ y $t = t(x_1, x_2, \ldots, x_n)$.

Así, en relación con las nuevas coordenadas de la EDP:

$$
\frac{\partial \nu }{\partial t} = 0 \Longrightarrow \nu = F(\theta_1, \theta_2, \ldots, \theta_{n-1})
$$

En términos de valores de $x$:

$$
u(x) = F(\theta(x)_1, \theta(x)_2, \ldots, \theta(x)_n)
$$

Recordemos que $\theta_i$ son constantes y diferenciables. Extendido a funciones diferenciables:

$$
\Phi(x)_1, \Phi(x)_2, \ldots, \Phi(x)_n
$$

constantes en las curvas características, tenemos

$$
u(x_1, x_2, \ldots, x_n) = F(\Phi(x_1, x_2, \ldots, x_n)_1, \Phi(x_1, x_2, \ldots, x_n)_2, \ldots, \Phi(x_1, x_2, \ldots, x_n)_n)
$$

Como caso particular, cada una de las primeras integrales $\Phi_i$ son soluciones de la EDP.

Ejemplo:

Resuelve la siguiente ecuación diferencial parcial:

$$
x_2 \frac{\partial u}{\partial x_1} + x_1 \frac{\partial u}{\partial x_2} + \frac{\partial u}{\partial x_3} = 0
$$

Obteniendo las curvas características:

$$
\frac{dx_1}{A_1} = \frac{dx_2}{A_2} = \ldots = \frac{dx_n}{A_n}
$$

$$
\frac{dx_1}{x_2} =\frac{dx_2}{x_1}=\frac{dx_3}{1}
$$

O bien
$$
\begin{equation}
    \frac{dx_1}{dx_3} =x_2
\end{equation}
$$
$$
\begin{equation}
    \frac{dx_2}{dx_3} =x_1
\end{equation}
$$

Sumando (1) y (2) 

$$
\frac{d(x_1 + x_2)}{dx_3} =x_1 + x_2
$$

$$
\int   \frac{d(x_1 + x_2)}{dx_3} =\int x_3
$$

$$
\ln (x_1 + x_2) = x_3 + C
$$

con $C$ constante

$$
x_1 + x_2=\beta   e ^{x_3 }
$$

con $\beta$ constante 

$$
\beta =(x_1 + x_2) e ^{-x_3 }
$$

$$
\Longrightarrow \Phi(x_1,x_2,x_3)
$$

$$
\Phi_1= (x_1+x_2)e ^{-x_3 }
$$

Restando (2) a (1) tenemos :

$$
\Phi_2= (x_2-x_1)e ^{x_3 }
$$

Ejemplo:

Resuelve el siguiente problema de Cauchy:

$$
y \frac{\partial u}{\partial x} - x \frac{\partial u}{\partial y} = 0
$$

con $u(x, 0) = x^2$.

primero planteamos las ecuaciones de las curvas caracteristicas 

$$
\frac{dx_1}{A_1} =\frac{dx_2}{A_2}
$$

$$
\Longrightarrow \frac{dx}{y} =\frac{dy}{-x}
$$

resolviendo 

$$
-xdx=ydy
$$

$$
-\frac{x^2}{2} =\frac{y^2}{2}+C_1
$$

Con $C_1$ constante 

$$
-\frac{x^2}{2} -\frac{y^2}{2}=C_1
$$

$$
-x^2 -y^2=2C_2
$$

$$
x^2 +y^2=-2C_2
$$

$$
x^2 +y^2=C_3
$$

Con $C_3=-2C_2$ 

$$
\Longrightarrow \Phi=x^2 +y^2
$$

$$
u(x,y)=f(\Phi (x,y))
$$

Aplicando el datode cauchy   $u(x,0)=x^2$

Igualando :

$$
f(x^2)=x^2
$$

Es decir $f(z)=z$

$$
u(x,y)=f(\Phi (x,y))=\Phi (x,y)=x^2 +y^2
$$


## Ecuaciones diferenciales cuasilineales de primer orden en dimensión n $\geq$ 2

Ahora estamos interesados en el estudio de ecuaciones de la forma:

\begin{equation} 
  \sum_{i=1}^{n} A_i(x_1, x_2,...,x_n, u)\frac{\partial u}{\partial x_i} = A(x_1, x_2,...,x_n, u)
  (\#eq:cuasi)
\end{equation} 


$$\sum_{i=1}^{n} A_i(x_1, x_2,...,x_n, u)\frac{\partial u}{\partial x_i}-A(x_1, x_2,...,x_n, u) \frac{\partial u}{\partial u} =0$$

donde las funciones $A_i$ y $A$ están definidas en la región $\Omega \in \mathbb{R}^{n+1}$ y son diferenciables. A la EDP anterior le asociaremos la siguiente EDP auxiliar "lineal"  para $v$

\begin{equation} 
  \sum_{i=1}^{n} A_i(x_1, x_2,...,x_n, u)\frac{\partial v}{\partial x_i}+A(x_1, x_2,...,x_n, u) \frac{\partial v}{\partial u} =0
  (\#eq:cuas)
\end{equation} 

```{theorem}
Sea $v(x_1, x_2,..., x_n, u)$ solución de la ecuación \@ref(eq:cuas) y suponer que en la región \omega de las variables $x_1, x_2,...,x_n$ la ecuación $v(x_1, x_2,...,x_n,u)=0$ define la función 
\
$$u= \varphi(x_1, x_2,..., x_n)$$ 

tal que $\frac{\partial v}{\partial u} \bigg|_{u=\varphi} \neq 0$ $\forall (x_1, x_2,...,x_n) \in \omega$.

Entonces $u= \varphi(x_1, x_2,..., x_n)$ es solución de \@ref(eq:cuasi)

```

**Demostración:**

Consideremos $v(x_1,x_2, x_n,u)=0$ y derivando implicitamente:

$$\frac{\partial v}{\partial x_i} \frac{\partial x_i}{\partial x_i}+\frac{\partial v}{\partial u}\frac{\partial u}{\partial x_i}=0$$
$$ \frac{\partial v}{\partial u}\frac{\partial u}{\partial x_i}=- \frac{\partial v}{\partial x_i}$$

Si empleamos que $\frac{\partial v}{\partial u}\big|_{u=\varphi}\neq 0$ entonces: 
\begin{equation} 
  \frac{\partial u}{\partial x_i} =- \frac{\frac{\partial v}{\partial x_i}}{\frac{\partial v}{\partial u}\big|_{u=\varphi}}
  (\#eq:t)
\end{equation} 

Partiendo de \@ref(eq:cuasi) y usando la expresión \@ref(eq:t)

$$\sum_{i=1}^{n} A_i(x_1, x_2,...,x_n, u) \frac{\partial u}{\partial x_i}=-\sum_{i=1}^{n}A_i(x_1, x_2,...,x_n, u)  \cdot \frac{\frac{\partial v}{\partial x_i}}{\frac{\partial v}{\partial u}\big|_{u=\varphi}} $$

$$=-\sum_{i=1}^{n}A_i(x_1, x_2,...,x_n, u)  \frac{\partial v}{\partial x_i} \cdot\frac{1}{\frac{\partial v}{\partial u}\big|_{u=\varphi}} $$

De acurdo a \@ref(eq:cuas)

$$\sum_{i=1}^{n} A_i(x_1, x_2,...,x_n, u)\frac{\partial v}{\partial x_i}= -A(x_1, x_2,...,x_n, u) \frac{\partial v}{\partial u} \bigg|_{u=\varphi}$$

Entonces:

$$\sum_{i=1}^{n} A_i(x_1, x_2,...,x_n, u) \frac{\partial u}{\partial x_i}=- \biggl(-A(x_1, x_2,...,x_n, u) \frac{\partial v}{\partial u} \bigg|_{u=\varphi}\biggr) \cdot \frac{1}{\frac{\partial v}{\partial u}\big|_{u=\varphi}} $$

$$=A(x_1, x_2,...,x_n, u)$$

Entonces el estudio realizado para las EDP lineales se puede emplear paras las EDP cuasilineales. El sistema de las curvas caracteristicas ahora es: 

$$\frac{dx_1}{A_1}=\frac{dx_2}{A_2}= \cdot \cdot \cdot =\frac{dx_n}{A_n}= \frac{du}{A}$$

Donde las cantidades $A_i$ , $A$ son constantes en $\Omega$ y no son cero simultáneamente en puntos de $\Omega$

**Observación 1:**
A diferencia de las EDP lineales, las curvas características no estan en el espacio $(x_1,x_2,...,x_n)$ sino en el espacio $(x_1, x_2,...,x_n,u)$

**Observación 2:**
Cada superficie integral $u(x_1,x_2,...,x_n)$ de la EDP cuasilineal está constituida por curvas caracteristica. Por esto es que $u$ se construye de "pegar" curvas caracteristicas.

**Observación 3:**
De la EDP \@ref(eq:cuasi) observamos que el vector $(\nabla u, -1)$ es ortogonal al vector $(A_1, A_2, ..., A_n , A)$. Es decir:
$$A_1 \frac{\partial u}{\partial x_1}+ A_2\frac{\partial u}{\partial x_2}+ \cdot \cdot \cdot +  A_n\frac{\partial u}{\partial x_n}-A=0$$

**Ejemplo 1:**

Encontrar la ecuación de la superficie que satisface la EDP cuasilineal de primer orden: $4yz \frac{\partial z}{\partial x}+\frac{\partial z}{\partial y}+2y=0$ la cual pasa a travez de la elipse $y^2+z^2=1$ , $x+z=2$.

*Solución:*
Escribimos las ecuaciones que definen las curvas caracteristicas de la forma general de la EDP $A_1 \frac{\partial u}{\partial x_1} + A_2 \frac{\partial u}{\partial x_2}=A$ ,  además:
$$\frac{dx_1}{A_1}=\frac{dx_2}{A_2}=\frac{du}{A}$$

Para nuestro caso: 
$$x_1 = x | A_1=4yz$$
$$x_2 = y | A_2=1$$
$$u = z | A=-2y$$

Las relaciones que definen las curvas caracteristicas son: 
$$\frac{dx}{4yz}=\frac{dy}{1}=-\frac{dz}{2y}$$

Podemos trabajar con : 
$$dy = - \frac{dz}{2y} \text{ , } \frac{dx}{4yz}=-\frac{dz}{2y}$$

Integrando, tenemos:

$$-\int 2y dy = \int dz$$
$$-y^2+c=z$$
$$c=z+y^2$$
con $c$ constante. También se tiene:
$$dx=-2z dz$$
$$x= -z^2+c_2$$
$$c_2 =x+z^2$$
con $c_2$ constante.

Entonces la solución está dada por $\varphi(z+y^2,x+z^2)=0$

Al sumar  $y^2 - z^2 = 1$ y $x + z = 2$ se obtiene:
 
$$x+z+y^2+z^2=3$$

Mientras que al sumar $c=z+y^2$ con $c_2 =x+z^2$, tenemos:

$$x+z+y^2+z^2=c+c_2$$

Entonces $c+c_2=3$

De esta forma: $x+z+y^2+z^2=3$

$\therefore x+z+y^2+z^2-3=0$ es solución de la ecuación.


**Ejemplo 2:**

Considerar la EDP cuasilineal de primer orden:
$$x \frac{\partial u}{\partial x}+ y\frac{\partial u}{\partial y} = u- x^2-y^2$$
Encontrar:
* La solución general de esta ecuación.
* La integral de Cauchy a travez de la curva $x=1$ , $u=y^2+2y-1$
  
*Solución:*
$$\frac{dx}{x}=\frac{dy}{y}=\frac{du}{u-x^2-y^2}$$

Primero resolvemos $\frac{dx}{x}=\frac{dy}{y}$:

\begin{equation} 
  x=c_3y
  (\#eq:Ejemplo21)
\end{equation} 

$$c_3=\frac{x}{y}$$
con $c_3$ constante.

Ahora resolvemos: $\frac{dy}{y}=\frac{du}{u-x^2-y^2}$ :

Sea $r=x^2+y^2$ y usando la ecuación \@ref(eq:Ejemplo21), entonces:
$$r=y^2(c^2+1)$$

Por lo cual,

$$\frac{du}{dy}=\frac{u-x^2-y^2}{y} = \frac{1}{y}(u-r)=\frac{r}{y} \biggl[\biggl(\frac{u}{r}\biggr)-1\biggr]$$

Sea $v=\frac{u}{r} \Longrightarrow u=vr \Longrightarrow \frac{du}{dy}=\frac{r}{y} (v-1)$

Por otro lado $dr=2y(c^2+1)dy$ o bien $dy=\frac{1}{2y(c^2+1)}dr$ , así:
$$\frac{du}{dy}=\frac{d}{dy}(vr) =2y(c^2+1)\frac{d}{dr}(vr) = 2y(c^2+1)(v+r\frac{dv}{dr})$$

Igualamos las expresiones encontradas para $\frac{du}{dy}$

$$\frac{r}{y}(v-1)=2y(c^2+1)(v+ r\frac{dv}{dr})$$

Como $r= y^2(c^2+1)$ entonces:
$$\frac{y^2(c^2+1)}{y}(v-1)=2y(c^2+1)(v+r\frac{dv}{dr})$$
$$(v-1)=2(v+r\frac{dv}{dr})$$

$$v-1= 2v+2r\frac{dv}{dr}$$
$$-(v+1)=2r \frac{dv}{dr}$$
$$-\frac{dr}{r}=2\frac{dv}{1+v}$$

Integrando
$$-\ln|r| = 2\ln|1+v|+\ln|\mu|$$
con $\mu$ constante. Es decir:

$$- \frac{1}{2} \ln|r|-\ln|1+v|=\frac{1}{2}\ln|\mu|$$

$$-\biggl(\ln|r^{\frac{1}{2}}| + \ln|1+v|\biggr)= \ln|\mu^{\frac{1}{2}}|$$
$$\nu:=\mu^{\frac{1}{2}}$$

$$-\ln|r^\frac{1}{2}(1+v)|=\ln|\nu|$$
$$\Longrightarrow \frac{1}{r^\frac{1}{2}}(1+v)= \nu \Longrightarrow \frac{1}{r^\frac{1}{2}}=\nu (1+v)$$
$$\frac{1}{r^\frac{1}{2}}-\nu=v\nu$$

$$v=\frac{1}{\nu r^\frac{1}{2}}-1$$
$$\Longrightarrow \frac{u}{r}=\frac{1}{\nu r^\frac{1}{2}}-1$$
$$u=\frac{r^\frac{1}{2}}{\nu}-r$$

Sea $a=\frac{1}{\nu}$ entonces:
$$u=ar^\frac{1}{2}-r$$

Usando la definición de r:
$$u=a \sqrt{x^2+y^2}-(x^2+y^2)$$
$$a=\varphi\biggl(\frac{x}{y}\biggr)$$
$$\Longrightarrow u=\varphi\biggl(\frac{x}{y}\biggr) \sqrt{x^2+y^2}-(x^2+y^2)$$

Usando las condiciones de Cauchy, tenemos:
$$u(x=1,y)=\varphi\biggl(\frac{1}{y}\biggr) \sqrt{1+y^2}-(1+y^2)$$

y con base en la segundo condición: $u(x=1,y) = -y^2+2y-1$. Al igualar las ecuaciones, se obtiene:

$$\varphi \bigg(\frac{1}{y}\bigg)\sqrt{1-y^2}-1-y^2=-y^2+2y-1$$
$$\varphi \biggl(\frac{1}{y}\biggr)\sqrt{1+y^2}=2y$$
$$\varphi \biggl(\frac{1}{y}\biggr)=\frac{2y}{\sqrt{1+y^2}}$$

Lo cual implica que: 
$$\varphi\biggl(\frac{x}{y}\biggr)=\frac{2\frac{y}{x}}{\sqrt{1+(\frac{y}{x})^2}}= \frac{2\frac{y}{x}}{\frac{1}{x}\sqrt{x^2+y^2}}=\frac{2y}{\sqrt{x^2+y^2}}$$

Sustituyendo este resultado en $u(x,y)$:

$$u(x,y)=\frac{2y}{\sqrt{x^2+y^2}} \sqrt{x^2+y^2}-(x^2+y^2)$$
$$\therefore u(x,y)= 2y-(x^2+y^2)$$













## Ecuaciones diferenciales parciales de primer orden no lineales


$\textbf{Ecuaciones diferenciales parciales de primer orden no lineales}$ 

Una ecuación diferencial parcial (edp) de primer orden no lineal es una ecuación de la forma
$$
\begin{equation}
    F(x, y, z, p, q) = 0
\end{equation}
$$

donde $z = z(x, y)$ es la función desconocida de dos variables independientes $x$ y $y$, mientras que
$$
    p = \frac{\partial z}{\partial x} \quad \text{y} \quad q = \frac{\partial z}{\partial y}
$$

La edp (1) tiene tres tipos de soluciones: la completa, la singular y la general.

La \textbf{solución completa} es una solución de (1) la cual depende de dos constantes arbitrarias e independientes,$a$ y $b$ así que se puede escribir
$$
\begin{equation}
    V(x, y, z, a, b) = 0
\end{equation}
$$

$\textbf{La solución singular}$ es una solución de $(1)$ que no depende ni de constantes arbitrarias ni de funciones arbitrarias. Cuando existe la solución singular, esta se obtiene de la solución completa $(2)$ por eliminación de $a$ y $b
$ del siguiente sistema de tres ecuaciones.


$$
V(x,y,z,a,b)=0
$$
$$
\frac{\partial V}{\partial a}(x,y,z,a,b)=0
$$
$$
\frac{\partial V}{\partial b}(x,y,z,a,b)=0
$$

la solucion general: es solucion de $(1)$ que depende de la funcion arbitraria.Ssi lasolucion completa de $(1)$ esta dada por $(z)$ entonces la solucion general esta dada por el sisitema de dos ecuaciones:

$$
V(x,y,z,a,b(a))=0
$$
$$
\frac{\partial V}{\partial a}(x,y,z,a,b(a)) + 
\frac{\partial V}{\partial b}(x,y,z,a,b(a))b ^\prime (a)=0
$$

donde $b(a)$ es una funcion arbitraria.



### Ecuaciones diferenciales totales 

Se llama ecuacion diferencial total o ecuacion de Pfaff a una ecuacion de la forma :

$$
dG(x,y,z)=P(x,y,z)dx+Q(x,y,z)dy+R(x,y,z)dz=0 
$$

con $P(x,y,z),Q(x,y,z) y R(x,y,z)$ son derivables respectoa todas sus variables.

La expresión (1) es integrable si existe una función $\mu(x,y,z)$, conocida como factor integrable, tal que:
$$
\mu(x,y,z) \left( P(x,y,z) \, dx + Q(x,y,z) \, dy + R(x,y,z) \, dz \right)
$$
es una diferencial exacta, es decir,
$$
\mu(x,y,z) \left( P(x,y,z) \, dx + Q(x,y,z) \, dy + R(x,y,z) \, dz \right) = d(U(x,y,z))
$$
$\textit{Nota:}$ En el caso en que $U$ sea constante se retoma la ecuación $(1)$.

Para el caso especial $U(x,y,z) = c$, $c$ constante, se recupera la ec. (1) y $U(x,y,z) = C$ es solución general de la ecuación de Pfaff.

$\textbf{Teorema \#1:}$ La condición necesaria y suficiente para que la EDP $P(x,y,z) \, dx + Q(x,y,z) \, dy + R(x,y,z) \, dz = 0$ sea integrable es que :
$$
\vec{A}\cdot (\nabla  \times \vec{A})
$$

DEMOSTRACION

Si la ecuacion $dG(x,y,z)=P(x,y,z)dx+Q(x,y,z)dy+R(x,y,z)dz=0$, con $c$ cosntante tal que :

$$
 \frac{\partial f}{\partial x}dx + \frac{df}{dy}dy + \frac{\partial f}{\partial z} {dz}= 0
$$
donde :
$$
 \frac{\partial f}{\partial x}=\mu(x,y,z)P(x,y,z)
$$
$$
 \frac{\partial f}{\partial y}=\mu(x,y,z)Q(x,y,z)
$$
$$
 \frac{\partial f}{\partial z}=\mu(x,y,z)R(x,y,z)
$$

$$
\biggl(\frac{df}{dx}, \frac{df}{dy},  \frac{df}{dz}\biggr)=\mu(x,y,z)(P,Q,R)
$$
$$\nabla f =\mu \vec{A}$$

usando el hecho de que $\nabla \times (\nabla  f)=\vec{0}$


$$
\Longrightarrow \nabla \times (\nabla  f)=\nabla \times (\nabla  \mu \vec{A})=\vec{0}
$$

Entonces
$$
\nabla \times (\mu \vec{A}) = \vec{0}
$$
Además,
$$
\mu \vec{A} \cdot \left( \nabla \times (\mu \vec{A}) \right) = 0
$$
es decir,
$$
\vec{A} \cdot \left( \nabla \times \vec{A} \right) = 0
$$
(se demostrará en la tarea con la idea de la siguiente demostración).

$\textbf{Obs \#1:}$
$ \nabla \times \vec{A} = \vec{0}$ implica que:

$$
\frac{\partial P}{\partial y} = \frac{\partial Q}{\partial x}, \quad \frac{\partial P}{\partial z} = \frac{\partial R}{\partial x}, \quad \frac{\partial Q}{\partial z} = \frac{\partial R}{\partial y}
$$

$$
\nabla \times \vec{A} =
\begin{vmatrix}
\hat{i} & \hat{j} & \hat{k} \\
\frac{\partial}{\partial x} & \frac{\partial}{\partial y} & \frac{\partial}{\partial z} \\
P & Q & R \\
\end{vmatrix}
$$

$$
= \hat{i} \left( \frac{\partial R}{\partial y} - \frac{\partial Q}{\partial z} \right) - \hat{j} \left( \frac{\partial R}{\partial x} - \frac{\partial P}{\partial z} \right) + \hat{k} \left( \frac{\partial Q}{\partial x} - \frac{\partial P}{\partial y} \right) = \vec{0}
$$

$\textbf{Obs \#2:}$ 
$\vec{A} \cdot \left( \nabla \times \vec{A} \right) = 0$ implica que:

$$
P \left( \frac{\partial Q}{\partial z} - \frac{\partial R}{\partial y} \right) + Q \left( \frac{\partial R}{\partial x} - \frac{\partial P}{\partial z} \right) + R \left( \frac{\partial P}{\partial y} - \frac{\partial Q}{\partial x} \right) = 0
$$



### Metodo general de integracion de una ecuacion Pfaff

1) Considerar una variable como parametro constante sin perdida de generalidad, se elige z constante , entonces 
$$
dz=0
$$

de esta forma se tiene :

$$
P(x,y,z)dx+Q(x,y,z)dy=0
$$

debemos encontrar G(x,y,z) tal que :
$$
dG(x,y,z)=P(x,y,z)dx+Q(x,y,z)dy
$$

2) Buscamos un factor integrante $\mu (x,y,z)$ tal que 

$$
\mu (x,y,z)P(x,y,z)=\frac{\partial G}{\partial x}(x,y,z)
$$
$$
\mu (x,y,z)Q(x,y,z)=\frac{\partial G}{\partial y}(x,y,z)
$$

3) Resolvemos la ecuacion diferencial 

$$
dG(x,y,z)=P(x,y,z)dx+Q(x,y,z)dy+K(x,y,z)dz=0
$$

con 
$$
K(x,y,z)=\mu (x,y,z)R(x,y,z)-\frac{\partial G}{\partial z}(x,y,z)
$$
$\textbf{Ejemplo:}$ Verificar si la EDP es integrable y en caso afirmativo encontrar su solución:

$$
yz \, dx + (x z + y z^3) \, dy - 2xy \, dz = 0
$$

$\textbf{Solucion:}$

$$
\vec{A} \cdot (\nabla \times \vec{A}) = 0
$$

$$
\vec{A} = (P, Q, R) = (yz, xz + yz^3, -2xy)
$$

$$
\nabla \times \vec{A} =
\begin{vmatrix}
\hat{i} & \hat{j} & \hat{k} \\
\frac{\partial}{\partial x} & \frac{\partial}{\partial y} & \frac{\partial}{\partial z} \\
yz & xz + yz^3 & -2xy
\end{vmatrix}
$$

$$
= \hat{i} \left( \frac{\partial (-2xy)}{\partial y} - \frac{\partial (xz + yz^3)}{\partial z} \right) 
- \hat{j} \left( \frac{\partial (-2xy)}{\partial x} - \frac{\partial (yz)}{\partial z} \right) 
+ \hat{k} \left( \frac{\partial (xz + yz^3)}{\partial x} - \frac{\partial (yz)}{\partial y} \right)
$$

$$
= \hat{i} \left( -2x - (x + 3yz^2) \right) - \hat{j} \left( -2y - y \right) + \hat{k} (z - z)
$$

$$
= \hat{i} (-3x - 3yz^2) - \hat{j} (-3y)
$$

$$
= -\hat{i} (3x + 3yz^2) + \hat{j} (3y)
$$

Calculamos

$$
\vec{A} \cdot (\nabla \times \vec{A}) = 0
$$

$$
= (yz, xz + yz^3, -2xy) \cdot (-3x - 3yz^2, 3y, 0)
$$

$$
= yz (-3x - 3yz^2)+ xz+yz^3(3y)-2xy(0)
$$

$$=-3xyz-3y^2z^3+3yxz+3y^2z^3=0$$
$\therefore$ La EDP es integrable.

1) Consideremos a $y$ como párametro constante, entonces $dy=0$ y:
   
$$yzdx-2xydz=0$$
$$\Longrightarrow zdx-2x dz=0$$

Dividiendo con $xz$:
$$\frac{dx}{x}-2\frac{dz}{z}=0$$

Integrando:
$$\int \frac{dx}{x}- 2\int \frac{dz}{z}=0$$

$$\ln|x|-2\ln|z|=\ln|c|$$

con $c$ constante.

$$\Longrightarrow \ln\biggl|\frac{x}{z^2}\biggr|=\ln|c|$$
$$\Longrightarrow \frac{x}{z^2}=c$$
Es decir $G(x,y,z)=\frac{x}{z^2}$


2) Además :

$$
\frac{\partial G}{\partial x}=\mu P
$$
$$
\Longrightarrow  \frac{\partial }{\partial x}(\frac{x}{z^2})=\mu (xy)
$$
$$
\frac{x}{z^2}=\mu (xy)
$$
$$
\mu =\frac{1}{yz^3}
$$

Tambien se determina:
$$
K(x,y,z) =\mu Q - \frac{\partial G}{\partial y}
$$
$$
=\frac{1}{yz^3}(xz+yz^3)-\frac{\partial }{\partial y}(\frac{x}{z^2})
$$
$$
=\frac{x}{yz^2}+1-0
$$
$$
=\frac{G}{y}+1
$$

3) La ecuacion diferencia parciales se escribe como :
$$
 dG + Kdy =0
$$

es decir :

$$
dG+(\frac{G}{y}+1) dy=0
$$
$$
\frac{dG}{dy}+\frac{G}{y}+1=0
$$


multiplicamos por y

$$
\Longrightarrow  \frac{d}{dy}y+(G)+y=0
$$
$$
\Longrightarrow  \frac{d}{dy}(yG)+\frac{d}{dy}(\frac{1}{z}y^2)=0
$$

es decir

$$
\frac{d}{dy}(yG+\frac{1}{z}y^2)=0
$$
$$
\Longrightarrow  \ yG+\frac{1}{z}y^2=a
$$

con $a$= constante 

Resolviendo para G

$$
G=\frac{a}{y}-\frac{1}{z}y
$$

ya que $G=G=\frac{x}{z^2}$  

igualando 

$$
\frac{x}{z^2}=\frac{a}{y}-\frac{1}{z}y
$$

$$
\therefore a=\frac{yx}{z^2}+\frac{1}{z}y^2
$$

































### El método de Lagrange - Charpit

Consideremos la EDP de primer orden no lineal de la forma:

$$
\begin{equation}
  F(x, y, u, p, q) = 0
\end{equation}
$$


Donde $u = u(x,y)$, $p = \frac{\partial u}{\partial x}, q =\frac{\partial u}{\partial y}$

La idea principal del método de Lagrange - Charpit para obtener la solución completa es encontrar una función $\Phi$ de la forma:

$\Phi (x,y,u,p,q) = a$,  con a una constante arbitraria 

Las funciones $F = 0$ y $ \Phi = a$ serán tales que que permitan resolver para p y q.

$$p = \gamma (x,y,u,a)$$
$$q = \gamma (x,y,u,a)$$

De la definición de p y q tenemos:

$$\frac{\partial p}{\partial y} = \frac{\partial}{\partial y} (\frac{\partial u}{\partial x}) = \frac{\partial}{\partial x} (\frac{\partial u}{\partial y}) = (\frac{\partial q}{\partial x}) $$

Además de la ecuación de Pfaff.

$$du = pdx + qdy$$

Satisface la condición de integrabilidad completa y su solución depende de otra constante arbitraria $b$. Por lo tanto se puede escribir:

$$V(x,y,u,a,b) = 0$$

Esta ecuación nos proporciona la solución completa de la EDP de primer orden no lineal.

$$F(x,y,u,p,q) = 0$$

Derivamos respecto $x$.

$0 = \frac{dF}{\partial x} = \frac{\partial F}{\partial x} \frac{dx}{dx} + \frac{\partial F}{\partial y} \frac{dy}{dy} + \frac{\partial F}{\partial x} \frac{\partial u}{\partial x} + \frac{\partial F}{\partial p} \frac{\partial p}{\partial x} + \frac{\partial F}{\partial q} \frac{\partial q}{\partial x}$, considerando que $(x,y)$ son independientes.

$$\frac{\partial F}{\partial x} + \frac{\partial F}{\partial u} (p) + \frac{\partial F}{\partial p} \frac{\partial p}{\partial x} + \frac{\partial F}{\partial q} \frac{\partial q}{\partial x}$$

$$F_x + F_u p + F_p p_x + F_q p_y = 0$$

$$F_p p_x + F_q p_y = - (F_x + F_u p)$$

Derivamos respecto $y$.

$\frac{dF}{\partial y} = \frac{\partial F}{\partial x} \frac{dx}{dy} + \frac{\partial F}{\partial y} \frac{dy}{dy} + \frac{\partial F}{\partial u} \frac{\partial u}{\partial y} + \frac{\partial F}{\partial p} \frac{\partial p}{\partial y} + \frac{\partial F}{\partial q} \frac{\partial q}{\partial y}$, considerando que $(x,y)$ son independientes.

$$\frac{\partial F}{\partial y} + \frac{\partial F}{\partial u} (q) + \frac{\partial F}{\partial p} \frac{\partial q}{\partial x} + \frac{\partial F}{\partial q} \frac{\partial q}{\partial y}$$

$$F_y + F_u q + F_q q_x + F_q q_y = 0$$

$$F_p q_x + F_q q_y = - (F_y + F_u q)$$

Observación: Estas expresiones son EDP cuasilineales para p y q.

$4F_p \frac{\partial p}{\partial x} + F_q \frac{\partial p}{\partial y} = - (F_x + F_u p)$$

$$\frac{dx}{F_p} = \frac{dy}{F_q} = - \frac{dp}{F_x + F_u p}$$

$$dy = \frac{F_q}{F_p} dx$$

$$F_p \frac{\partial p}{\partial x} + F_q \frac{\partial p}{\partial y} = - (F_y + F_u q)$$

$$\frac{dx}{F_p} = \frac{dy}{F_q} = - \frac{dq}{F_y + F_u q}$$

$$\frac{dx}{F_p} = \frac{dy}{F_q} = - \frac{dp}{F_x+F_up} = - \frac{dq}{F_y + F_u q} $$

Además considerando que:

$du = \frac{\partial u}{\partial x} dx + \frac{\partial u}{\partial y} dy = pdx + qdy$, con base en (1).

$$du = pdx + q \frac{F_q}{F_p} dx = \frac{F_p p + q F_q}{F_p} dx$$

Entonces:

$$du = \frac{F_p p + q F_q }{F_p} dx$$

$$\frac{dx}{F_p} = \frac{du}{F_p p + q F_q}$$

Por lo tanto:

$$\frac{dx}{F_p} = \frac{dy}{F_q} = - \frac{-dp}{F_x + F_u p} = - \frac{dq}{F_y+F_up} = \frac{du}{F_p p + q F_q}$$

Este sistema de ecuaciones se conoce cono ecuaciones de Charpit.

**Ejemplo 1**

Encontrar la solución general de 

$$u^3 = pq^2$$

Solución.

$F(x,y,u,p,q) = u^3 - pq^2 = 0$

$F_p = -q^2$

$F_q = -2pq$

$F_x = 0$

$F_u = 3u^2 $

$F_y = 0$

Nuestras ecuaciones de Charpit son

$$- \frac{dx}{q^2} = - \frac{dy}{2pq} = - \frac{dp}{3u^2 p} = - \frac{dq}{3u^2 q} = \frac{du}{-pq^2 p + q(-2pq)}$$

Observación.

 $$-pq^2 p + q(-2pq) = -3pq^2, pq^2 = u^3$$

$$- \frac{dx}{q^2} = - \frac{dy}{2pq} = - \frac{dp}{3u^2 p} = - \frac{dq}{3u^2 q} = - \frac{du}{3u^3}$$

Considerando la igualdad:

$$\frac{dq}{3u^2 q} = \frac{du}{3u^3}$$

$$\frac{dq}{q} = \frac{du}{u}$$

Integrando se obtiene:

$$ln |q| = ln |u| + ln |c|$$

$$q = uc$$

$$\frac{\partial u}{\partial y} = uc$$

$$\frac{du}{u} = cdy$$

$ln |u| = cy + a$, con a una constante 

$$u = e^{cy+a} = e^{a} e^{cy} + f(x)$$

$$u = Ae^{cy} + f(x)$$

Consideramos ahora la igualdad:

$$\frac{dp}{3u^2 p} = \frac{du}{3u^3}$$

$$\frac{dp}{p } = \frac{du}{u}$$

$ln |p| = ln |u| + ln |b|$ , con b una constante 

$$p = ub$$

Tenemos entonces:

$$q = uc$$

$$p = ub$$

$$u = exp(cy) + f(x)$$

$u = exp(bx) + g(y) + \tau$, con $\tau$ una constante

Por lo tanto la solución general de nuestra ecuación es:

$u = e^{bx} + e^{cy} + \tau$, con $b, c = 1$

**Ejemplo 2**

Hallar la solución de la EDP no lineal 

$$xp^2 - up + q^2 = 0$$

$$-xp^2 + q^2 = up$$

Solución

$$F(x,y,u,p,q) = xp^2 - up + q^2 = 0$$

$$F_x = p^2$$

$$F_y = 0$$

$$F_p = 2xp - u$$

$$F_q = 2q$$

$$F_u = -p$$

Además:

$$pF_p + qF_q = p(2xp-u) + q(2q) = 2xp^2 -up +2q^2 = 2(xp^2 + q^2) -up = 2up-up=up$$

$$F_x + F_u p = p^2 + p(-p) = 0$$

$$F_y + F_u q = 0 -p (q) = -pq$$

Como $F_x + F_u p = 0$ no podemos escribir las ecuaciones de Charpit tal como las tenemos. Si regresamos en el proceso donde se obtienen las ecuaciones tenemos.

$$F_p P_x + F_y P_y = - (F_x + F_u p) = 0$$

Que sería la ecuación cuasilineal para p, pero $F_p \neq F_q$

Entonces $(F_q, F_p) (p_x, p_y) = 0$

La única posibilidad es que:

$p_x = 0$, $p_y = 0$, entonces p es una constante 

$p =c_1$, con $c_1$ una constante

El sistema se reduce considerando $du = pdx + qdy$, de la ecuación diferencial parcial no lineal, despejamos $q^2$.

$$q^2 = -xp^2 + up = p(-xp+u)$$

Sustituyendo en $du$

$$du = pdx + \sqrt{p(-xp+u)}dy$$

$$du - pdx = \sqrt{p} \sqrt{(u-px)} dy$$

$$d(u-px) = \sqrt{p} \sqrt{(u-px)} dy$$

$$\frac{d(u-px)}{\sqrt{(u-px)}} = \sqrt{p} dy$$

Integramos:

$$\int \frac{d(u-px)}{\sqrt{(u-px)}} = \int \sqrt{p} dy$$

Sea $z=u-px$, entonces:

$$\int \frac{dz}{z} = \int \sqrt{p} dy$$

$$\int \frac{1}{z^{\frac{1}{2}}} dz = \int \sqrt{p} dy$$

Entonces:

$2z^{\frac{1}{2}} = \sqrt{p}y + i$, con i una constante 

$(u-px)^\frac{1}{2} = \frac{\sqrt{p}y + w}{2}$, con w una constante

$$(u-px) = (\frac{\sqrt{p}y + w}{2})^2$$

Por lo tanto:

$$u = (\frac{\sqrt{p}y + w}{2})^2 + p(x)$$
